# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: ^packages/agentsociety2/docs/
      - id: end-of-file-fixer
        exclude: ^packages/agentsociety2/docs/
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=512]
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: ^packages/agentsociety2/
      - id: ruff-format
        files: ^packages/agentsociety2/

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.4.2
    hooks:
      - id: prettier
        types_or: [ts, tsx, js, jsx, json, yaml, css, html]
        exclude: ^(frontend/node_modules/|extension/node_modules/|packages/agentsociety/|packages/agentsociety-community/|packages/agentsociety-benchmark/|packages/agentsociety/docs/|frontend/public/monaco-editor/)

  - repo: https://github.com/nick-lockhart/pre-commit-git-cliff
    rev: 0.6.0
    hooks:
      - id: git-cliff-check
        args: [--config, cliff.toml, --tag-pattern, "agentsociety2-v[0-9]+.[0-9]+.[0-9]+"]
