"""Analysis harness: state, validators, and CLI helpers for staged experiment analysis."""

from .attestation import PHASE_RUBRIC_KEYS
from .capabilities import (
    AnalysisCapabilityStatus,
    analysis_capability_statuses,
    capability_payload,
    get_eda_capability_status,
)
from .guidance import (
    get_chart_scaffold,
    get_harness_guidance,
    get_payload_template,
    list_payload_templates,
)
from .execution import (
    OperationFailure,
    OperationOutcome,
    OperationRunReceipt,
    execute_operation,
    list_run_receipts,
    load_run_receipt,
    operation_execution_key,
    recover_interrupted_runs,
    unresolved_retryable_runs,
)
from .models import (
    AnalysisPhase,
    AnalysisPlan,
    AttestationStatus,
    Claim,
    ClaimMode,
    FigureContract,
    GateReport,
    HypothesisAnalysisState,
    PhaseAttestation,
    PhaseCheckpoint,
    ReleaseStatus,
    SynthesisAnalysisState,
    TableCheck,
    ValidationIssue,
    ValidationResult,
)
from .operations import (
    AnalysisInputGroup,
    AnalysisInputSpec,
    AnalysisOperationSpec,
    get_operation_spec,
    operation_registry,
    operation_specs_for_phase,
    workflow_operations_by_phase,
)
from .paths import (
    analysis_locks_dir,
    analysis_operation_lock_path,
    analysis_run_path,
    analysis_runs_dir,
    hypothesis_analysis_dir,
    hypothesis_claims_path,
    hypothesis_plan_path,
    hypothesis_prepare_manifest_path,
    hypothesis_state_path,
    synthesis_analysis_dir,
    synthesis_state_path,
)
from .preflight import OperationAvailability, evaluate_operation_availability
from .preparation import (
    PreparationManifest,
    PreparationStepPlan,
    PreparationStepRecord,
    build_prepare_produce_plan,
)

__all__ = [
    "PHASE_RUBRIC_KEYS",
    "AnalysisCapabilityStatus",
    "analysis_capability_statuses",
    "capability_payload",
    "get_eda_capability_status",
    "get_chart_scaffold",
    "get_harness_guidance",
    "get_payload_template",
    "list_payload_templates",
    "OperationFailure",
    "OperationOutcome",
    "OperationRunReceipt",
    "execute_operation",
    "list_run_receipts",
    "load_run_receipt",
    "operation_execution_key",
    "recover_interrupted_runs",
    "unresolved_retryable_runs",
    "AnalysisPhase",
    "AnalysisPlan",
    "AttestationStatus",
    "Claim",
    "ClaimMode",
    "FigureContract",
    "GateReport",
    "HypothesisAnalysisState",
    "PhaseAttestation",
    "PhaseCheckpoint",
    "ReleaseStatus",
    "SynthesisAnalysisState",
    "TableCheck",
    "ValidationIssue",
    "ValidationResult",
    "AnalysisOperationSpec",
    "AnalysisInputSpec",
    "AnalysisInputGroup",
    "get_operation_spec",
    "operation_registry",
    "operation_specs_for_phase",
    "workflow_operations_by_phase",
    "OperationAvailability",
    "evaluate_operation_availability",
    "PreparationManifest",
    "PreparationStepPlan",
    "PreparationStepRecord",
    "build_prepare_produce_plan",
    "analysis_locks_dir",
    "analysis_operation_lock_path",
    "analysis_run_path",
    "analysis_runs_dir",
    "hypothesis_analysis_dir",
    "hypothesis_claims_path",
    "hypothesis_plan_path",
    "hypothesis_prepare_manifest_path",
    "hypothesis_state_path",
    "synthesis_analysis_dir",
    "synthesis_state_path",
]
